/**
 * @manya/ledger — key generation, import/export, fingerprints.
 *
 * Self-contained: implements locally the subset of key utilities needed by
 * @manya/ledger (ECDSA P-256 default, RSA-PSS optional). Does NOT import
 * from `@manya/keyring` or any other sibling workspace.
 *
 * Copyright 2024 Manya Hael Foundation. All rights reserved.
 * Conceived, directed, and owned by Uviwe Menyiwe (Azura Daemon), founder
 * of the Manya Hael Foundation.
 *
 * Licensed under the Apache License, Version 2.0.
 */

import * as crypto from 'crypto';
import { LedgerError } from '../errors.js';
import type { KeyAlgorithm, SignatureAlgorithm } from '../types.js';
import { sha256 } from './hashing.js';

/** RSA modulus length used by default (>= 3072 bits per NIST SP 800-57). */
export const DEFAULT_RSA_MODULUS = 3072;
/** RSA public exponent. */
export const DEFAULT_RSA_EXPONENT = 65537;
/** EC named curve used for ECDSA. */
export const DEFAULT_EC_CURVE = 'prime256v1';

/** Optional parameters for {@link generateKeyPair}. */
export interface GenerateKeyPairOptions {
  /**
   * RSA modulus length in bits. Ignored for ECDSA. Defaults to
   * {@link DEFAULT_RSA_MODULUS}.
   */
  rsaModulusBits?: number;
  /** RSA public exponent. Defaults to {@link DEFAULT_RSA_EXPONENT}. */
  rsaPublicExponent?: number;
  /**
   * EC curve. Currently only `prime256v1` (NIST P-256) is supported.
   * Defaults to {@link DEFAULT_EC_CURVE}.
   */
  ecCurve?: 'prime256v1';
}

/** Key pair generated by {@link generateKeyPair}. */
export interface GeneratedKeyPair {
  publicKey: crypto.KeyObject;
  privateKey: crypto.KeyObject;
  /** Resolved signature algorithm. */
  algorithm: SignatureAlgorithm;
}

/**
 * Map a {@link KeyAlgorithm} to its concrete {@link SignatureAlgorithm}.
 */
export function algorithmFor(algo: KeyAlgorithm): SignatureAlgorithm {
  switch (algo) {
    case 'rsa':
      return 'rsa-pss';
    case 'ecdsa':
      return 'ecdsa-p256';
    default:
      throw new LedgerError(`unknown key algorithm: ${algo as string}`);
  }
}

/**
 * Map a `crypto.KeyObject`'s `asymmetricKeyType` to a {@link SignatureAlgorithm}.
 * Throws if the key type is not RSA or EC (P-256).
 */
export function algorithmForKey(key: crypto.KeyObject): SignatureAlgorithm {
  let type: crypto.KeyType | undefined;
  try {
    type = key.asymmetricKeyType;
  } catch (err) {
    throw new LedgerError(
      'algorithmForKey: cannot read key type: ' + (err as Error).message,
      'KEY_TYPE_ERROR',
      err
    );
  }
  if (type === 'rsa') return 'rsa-pss';
  if (type === 'ec') {
    let details: crypto.AsymmetricKeyDetails | undefined;
    try {
      details = key.asymmetricKeyDetails;
    } catch {
      // Fall through to default.
    }
    if (details && (details as { namedCurve?: string }).namedCurve) {
      const curve = (details as { namedCurve?: string }).namedCurve;
      if (curve !== 'P-256' && curve !== 'prime256v1' && curve !== 'secp256r1') {
        throw new LedgerError(
          `algorithmForKey: only NIST P-256 is supported, got ${curve}`
        );
      }
    }
    return 'ecdsa-p256';
  }
  throw new LedgerError(
    `algorithmForKey: unsupported key type: ${type ?? 'unknown'} (only rsa and ec are supported)`
  );
}

/**
 * Generate a key pair.
 *
 * Defaults to ECDSA P-256 (the spec mandates P-256 support). RSA-PSS 3072
 * is available for deployments that require it.
 *
 * @param algo - `'ecdsa'` (default) or `'rsa'`.
 * @param opts - Optional parameters.
 * @returns Key pair + resolved signature algorithm.
 * @throws {@link LedgerError} on any failure.
 */
export function generateKeyPair(
  algo: KeyAlgorithm = 'ecdsa',
  opts: GenerateKeyPairOptions = {}
): GeneratedKeyPair {
  try {
    let publicKey: crypto.KeyObject;
    let privateKey: crypto.KeyObject;
    if (algo === 'rsa') {
      ({ publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
        modulusLength: opts.rsaModulusBits ?? DEFAULT_RSA_MODULUS,
        publicExponent: opts.rsaPublicExponent ?? DEFAULT_RSA_EXPONENT,
      }));
    } else if (algo === 'ecdsa') {
      const curve = opts.ecCurve ?? DEFAULT_EC_CURVE;
      if (curve !== 'prime256v1') {
        throw new LedgerError(
          `unsupported EC curve: ${curve}. Only 'prime256v1' (NIST P-256) is supported.`
        );
      }
      ({ publicKey, privateKey } = crypto.generateKeyPairSync('ec', {
        namedCurve: curve,
      }));
    } else {
      throw new LedgerError(`unknown key algorithm: ${algo as string}`);
    }
    return { publicKey, privateKey, algorithm: algorithmFor(algo) };
  } catch (err) {
    if (err instanceof LedgerError) throw err;
    throw new LedgerError('key generation failed: ' + (err as Error).message, 'KEY_GENERATION_ERROR', err);
  }
}

/**
 * Import a public or private key from PEM.
 *
 * @param pem - PEM-encoded key.
 * @param type - `'public'` or `'private'`.
 */
export function importKeyPem(
  pem: string,
  type: 'public' | 'private'
): crypto.KeyObject {
  try {
    if (type === 'public') {
      return crypto.createPublicKey(pem);
    }
    return crypto.createPrivateKey(pem);
  } catch (err) {
    throw new LedgerError(
      `failed to import ${type} key from PEM: ${(err as Error).message}`,
      'KEY_IMPORT_ERROR',
      err
    );
  }
}

/**
 * Export a key as PEM (SPKI for public, PKCS#8 for private).
 *
 * @param key - KeyObject to export.
 * @param type - `'public'` or `'private'`.
 * @returns PEM string.
 */
export function exportKeyPem(
  key: crypto.KeyObject,
  type: 'public' | 'private'
): string {
  try {
    if (type === 'public') {
      return key.export({ type: 'spki', format: 'pem' }).toString('utf8');
    }
    return key.export({ type: 'pkcs8', format: 'pem' }).toString('utf8');
  } catch (err) {
    throw new LedgerError(
      `failed to export ${type} key to PEM: ${(err as Error).message}`,
      'KEY_EXPORT_ERROR',
      err
    );
  }
}

/**
 * Compute a hex-encoded SHA-256 key id of a public key.
 *
 * The key id is `sha256(spki-derepr)` — the SHA-256 of the public key's
 * SubjectPublicKeyInfo DER encoding. This is the same scheme used by
 * `@manya/attest`'s `getKeyFingerprint`, so cross-package references are
 * stable.
 *
 * Accepts either a KeyObject or a PEM string for convenience.
 *
 * @param publicKey - Public key (KeyObject or PEM string).
 * @returns 64-character hex string.
 */
export function getKeyId(publicKey: crypto.KeyObject | string): string {
  try {
    const keyObj =
      typeof publicKey === 'string'
        ? crypto.createPublicKey(publicKey)
        : publicKey;
    const der = keyObj.export({ type: 'spki', format: 'der' });
    return sha256(der).toString('hex');
  } catch (err) {
    throw new LedgerError(
      'getKeyId failed: ' + (err as Error).message,
      'KEY_ID_ERROR',
      err
    );
  }
}

/**
 * Sign `data` with `privateKey` and return a hex-encoded signature.
 *
 * The algorithm is inferred from the key type if `algo` is omitted
 * (ECDSA P-256 for `ec` keys, RSA-PSS for `rsa` keys).
 *
 * @param privateKey - Private KeyObject or PEM string.
 * @param data - Bytes to sign.
 * @param algo - Optional signature algorithm. Inferred from the key if omitted.
 * @returns Hex-encoded signature.
 * @throws {@link LedgerError} on any failure.
 */
export function sign(
  privateKey: crypto.KeyObject | string,
  data: Buffer,
  algo?: SignatureAlgorithm
): string {
  if (!Buffer.isBuffer(data)) {
    throw new LedgerError('sign: data must be a Buffer', 'SIGN_ERROR');
  }
  const key = asPrivateKey(privateKey);
  const resolvedAlgo = algo ?? algorithmForKey(key);
  try {
    if (resolvedAlgo === 'rsa-pss') {
      const sig = crypto.sign(SIGN_HASH, data, {
        key,
        padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
        saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST,
      });
      return sig.toString('hex');
    }
    if (resolvedAlgo === 'ecdsa-p256') {
      const sig = crypto.sign(SIGN_HASH, data, key);
      return sig.toString('hex');
    }
    throw new LedgerError(`unsupported signature algorithm: ${resolvedAlgo as string}`);
  } catch (err) {
    if (err instanceof LedgerError) throw err;
    throw new LedgerError('sign failed: ' + (err as Error).message, 'SIGN_ERROR', err);
  }
}

/**
 * Verify a `signature` over `data` against `publicKey`.
 *
 * Uses `crypto.timingSafeEqual` internally as a defense-in-depth constant-time
 * guard on the OpenSSL verify result. Returns `false` (rather than throwing)
 * for any malformed input or signature mismatch — callers that need to
 * distinguish bad signatures from bad inputs should catch {@link LedgerError}.
 *
 * @param publicKey - Public KeyObject or PEM string.
 * @param data - Original bytes.
 * @param signature - Hex-encoded signature (or Buffer).
 * @param algo - Optional signature algorithm. Inferred from the key if omitted.
 * @returns `true` iff the signature is valid.
 */
export function verify(
  publicKey: crypto.KeyObject | string,
  data: Buffer,
  signature: Buffer | string,
  algo?: SignatureAlgorithm
): boolean {
  if (!Buffer.isBuffer(data)) {
    throw new LedgerError('verify: data must be a Buffer', 'VERIFY_ERROR');
  }
  let signatureBuf: Buffer;
  if (typeof signature === 'string') {
    if (signature.length === 0 || !/^[0-9a-fA-F]+$/.test(signature)) {
      throw new LedgerError('verify: signature must be non-empty hex', 'VERIFY_ERROR');
    }
    try {
      signatureBuf = Buffer.from(signature, 'hex');
    } catch {
      throw new LedgerError('verify: signature must be hex-encoded', 'VERIFY_ERROR');
    }
  } else {
    signatureBuf = signature;
  }

  const key = asPublicKey(publicKey);
  const resolvedAlgo = algo ?? algorithmForKey(key);
  let ok: boolean;
  try {
    if (resolvedAlgo === 'rsa-pss') {
      ok = crypto.verify(
        SIGN_HASH,
        data,
        {
          key,
          padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
          saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST,
        },
        signatureBuf
      );
    } else if (resolvedAlgo === 'ecdsa-p256') {
      ok = crypto.verify(SIGN_HASH, data, key, signatureBuf);
    } else {
      throw new LedgerError(`unsupported signature algorithm: ${resolvedAlgo as string}`);
    }
  } catch (err) {
    if (err instanceof LedgerError) throw err;
    return false;
  }

  // Constant-time guard: derive a 1-byte result and compare with the expected
  // value using timingSafeEqual. This avoids any branch on the verified
  // boolean and serves as a defense-in-depth.
  const okByte = Buffer.from([ok ? 1 : 0]);
  const expected = Buffer.from([1]);
  return crypto.timingSafeEqual(okByte, expected);
}

/** Hash algorithm used for all signature operations. */
const SIGN_HASH = 'sha256';

/**
 * Convert a public key input (KeyObject or PEM string) into a KeyObject.
 */
function asPublicKey(key: crypto.KeyObject | string): crypto.KeyObject {
  if (typeof key === 'string') {
    try {
      return crypto.createPublicKey(key);
    } catch (err) {
      throw new LedgerError(
        'invalid public key PEM: ' + (err as Error).message,
        'VERIFY_ERROR',
        err
      );
    }
  }
  return key;
}

/**
 * Convert a private key input (KeyObject or PEM string) into a KeyObject.
 */
function asPrivateKey(key: crypto.KeyObject | string): crypto.KeyObject {
  if (typeof key === 'string') {
    try {
      return crypto.createPrivateKey(key);
    } catch (err) {
      throw new LedgerError(
        'invalid private key PEM: ' + (err as Error).message,
        'SIGN_ERROR',
        err
      );
    }
  }
  return key;
}
